version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - mysql_db:/var/lib/mysql
    env_file:
      - ./example.env
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 5

  redis:
    image: redis:latest
    restart: always

  migrations:
    build:
      context: ./OzonParseApp/
    command: sh -c "python manage.py migrate --noinput"
    env_file:
      - ./example.env
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./OzonParseApp/
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - ./example.env
    ports:
      - 80:8000

volumes:
  mysql_db: