DEFAULT_TIMEOUT = 10
PRODUCT_IN_LIST = 'yh6.tile-hover-target'
URL = 'https://www.ozon.ru/seller/1/products/'
PRODUCTS_ON_PAGE = 36
ATTRIBUTES_HEADER = 'n2j'
ATTRIBUTES_BLOCK = 'n3j'
ATTRIBUTES_ITEMS = 'dl[class^="nj7"]'
DISPLAY_WIDTH = 1920
DISPLAY_HEIGHT = 1080
